name: ulm_frontend
description: User Login Manager - Flutter Frontend with full RTL support
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.5
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^13.0.0
  
  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Localization & RTL
  intl: ^0.18.1
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Icons & Images
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Animations
  animations: ^2.0.8
  lottie: ^2.7.0
  
  # Utilities
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  
  # Charts & Data Visualization
  fl_chart: ^0.65.0
  
  # Date & Time
  flutter_datetime_picker_plus: ^2.0.1
  
  # Notifications
  flutter_local_notifications: ^16.2.0
  
  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  
  # Connectivity
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    # Localization files
    - assets/i18n/
    - assets/i18n/en.json
    - assets/i18n/he.json
    - assets/i18n/ar.json
    
    # Images
    - assets/images/
    - assets/images/logo.png
    
    # Flags for language selector
    - assets/flags/
    - assets/flags/il.png
    - assets/flags/us.png
    - assets/flags/sa.png
    
    # Animations
    - assets/animations/
  
  # Fonts that support RTL
  fonts:
    # Rubik - Great for Hebrew
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
    
    # Tajawal - Great for Arabic
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
    
    # Roboto - Default for English
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

# Custom path for shared resources
dependency_overrides:
  interface_resources:
    path: ../../../../shared/interface-resources/flutter
  localization:
    path: ../../../../shared/localization
